// flow-typed signature: 8e01893da90cd9f21e5dd0b2116f6a7b
// flow-typed version: <<STUB>>/stylelint-no-browser-hacks_v^1.2.1/flow_v0.85.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stylelint-no-browser-hacks'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stylelint-no-browser-hacks' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'stylelint-no-browser-hacks/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'stylelint-no-browser-hacks/lib/index.js' {
  declare module.exports: $Exports<'stylelint-no-browser-hacks/lib/index'>;
}
